import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]
[window]
padding = { y = 10, x = 10 }
decorations = "buttonless"
opacity = 0.8
dynamic_padding = true
dynamic_title = true

[font]
size = 14.0

normal = { family = "FiraCode Nerd Font", style = "Regular" }

bold = { family = "FiraCode Nerd Font", style = "Bold" }

italic = { family = "FiraCode Nerd Font", style = "Italic" }

bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }

[terminal]
osc52 = "CopyPaste"
