[window]
padding = { y = 20, x = 20 }
decorations = "buttonless"

[font]
size = 14.0

normal = { family = "FiraCode Nerd Font", style = "Regular" }

bold = { family = "FiraCode Nerd Font", style = "Bold" }

italic = { family = "FiraCode Nerd Font", style = "Italic" }

bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }

